[connections.streamlit_db]
type = "sql"
dialect = "mysql"
username = "root"
# password = "xxx"
host = "127.0.0.1"        # IP or URL
port = 3306               # Port number
database = "streamlit_db" # Database name
